name: Release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - shell: bash
        env:
          gpg_private_key: ${{ secrets.gpg_private_key }}
        run: |
          printf "%s" "$gpg_private_key" | gpg --import --batch --yes
      - name: Release with central-publishing-maven-plugin
        env:
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          maven_central_login: ${{ secrets.maven_central_login }}
          maven_central_pass: ${{ secrets.maven_central_pass }}
        run: mvn -B -s .mvn/settings.xml -P release deploy --file pom.xml
